### PR TITLE
Fix dict accesses in spacedock_adder

### PR DESCRIPTION
**Pull request by DasSkelett**
# Problem
The usual dict access problem :)
Dicts need accessing by `dict.get('something')`, not `dict.something`

# Changes
Replaced every dict access in `spacedock_adder.py` with a `.get()` access.

### CODE REVIEW

**Comment by HebaruSan** [comment]
I wish I had never learned Javascript.

**Comment by DasSkelett** [comment]
Huh, don't understand the error message, I think it's unrelated:
`  error: could not create 'build': Permission denied`

**Comment by HebaruSan** [comment]
Yeah, I don't think these changes could break the Docker build like that. But if there's a problem with it now, that might also cause problems after merge. Probably best to have @techman83 take a look.

**Comment by HebaruSan** [comment]
On second thought, let's just merge in case it does help. If not we can investigate then.

**Pull request merged**
