### PR TITLE
Add permissions for CI

### PR DESCRIPTION
**Pull request by techman83**
CI Required permission to add items to the queue, this has been applied already.

### CODE REVIEW

**Comment by HebaruSan** [comment]
So, I have no idea what this does...
it wasn't working? How does this tie to the new Action in a way it didn't previously? It looks like this just allows listing queues?

**Comment by techman83** [comment]
> So, I have no idea what this does...
> it wasn't working? How does this tie to the new Action in a way it didn't previously? It looks like this just allows listing queues?

I created a new user specifically for the Metadata CI and added it to the 'KspCkanCiMetadataGroup' permission group. It needs to be able to list the queues (to get the queue url) and add a message to the queue.

**Review by HebaruSan — APPROVED** [review]
OK, that makes sense. I suppose we'll find out if there are any problems!

**Comment by techman83** [comment]
Haha, it should be relatively pretty binary. Works or doesn't work :slightly_smiling_face:

**Pull request merged**
